
spring:
  profiles:
    active: dev
  application:
    name: mybaties_test

# 配置mybatis规则    可以不写全局；配置文件，所有全局配置文件的配置都放在configuration配置项中即可(这两个只能选一个)
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml  #在核心配置文件中指明全局配置文件位置

  #指明sql映射文件位置
  mapper-locations: classpath:mybaties/xml/*Mapper.xml

  configuration:
    #可以不在核心配置文件中指明全局配置文件位置，而直接在核心配置文件中改全局信息，开启驼峰命名
    map-underscore-to-camel-case: true

    #开启日志功能 ，，，，查看生产的sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件
pagehelper:
  helperDialect: mysql  #指定数据库，不指定的话会默认自动检测数据库类型
  reasonable: true
  #是否启动分页合理化。如果启用，当 pagenum < 1 时，会自动查询第一页的数据，当 pagenum > pges 时，自动查询最后一页数据；
  #不启用的，以上两种情况都会返回空数据，如果启用则 pageHelper可以自动拦截请求参数中的 pageNum，pageSize参数，否则需要使用 PageHelper.startPage(pageNum,pageSize) 方法调用。

  supportMethodsArguments: true  #默认为 false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。


  #用于从对象中根据属性名取值，可以配置 pageNum，pageSize，count，pageSizeZero，reasonable，不配置映射的用默认值，默认值为 pageNum=pageNum；
  #pageSize=pageSize；count=countSql；reasonable=reasonable；pageSizeZero=pageSizeZero
  params: count=countSql

server:
  port: 8003