spring:
  application:
    name: shardingjdbcDemo
  main:
    allow-bean-definition-overriding: true

  shardingsphere:
    #数据源信息
    datasource:
      #名称为dbsource-0的数据源
      dbsource-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/db1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
      #名称为dbsource-1的数据源
      dbsource-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/db2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
      names: dbsource-0,dbsource-1
    #规则的配置
    rules:
      sharding:
        tables:
          #配置表的规则
          t_order:
            actual-data-nodes: dbsource-$->{0..1}.t_order_$->{0..1}
            #分库策略
            database-strategy:
              standard: # 用于单分片键的标准分片场景
                sharding-column: user_id
                sharding-algorithm-name: db-inline
            #分表策略
            table-strategy:
              #标准策略
              standard:
                sharding-column: user_id
                sharding-algorithm-name: table-inline


        #分片算法
        sharding-algorithms:
          db-inline:
            type: MOD
            props:
              sharding-count: 2  # 表示有2个分片库数量
          table-inline:
            type: MOD
            props:
              sharding-count: 2  # 表示有2个分片表数量

    props:
      sql-show: true
      sql-comment-parse-enabled: true



