server:
  port: 8001
spring:
  profiles:
    active: dev

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.xufei.springcloud.openfeign.feign.OrderFeignService: debug

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
#超时控制
feign:
  client:
    config:
      default:
        connectTimeout: 9000
        readTimeout: 9000