server:
  port: 8016

logging:
  config: classpath:logback-sendMail.xml
  #logback-sendMail.xml整合了邮件报警，logback-spring.xml没有整合邮件报警
spring:
  #邮箱配置
  mail:
    error:
      subject: '错误日志报警'
      to: 2458918040@qq.com
    #坑爹的地方：host 通道个人邮箱和企业邮箱通道不同。163的个人邮箱：smtp.163.com ，企业邮箱：smtp.qiye.163.com
    # 腾讯的，个人smtp.qq.com， 企业的：smtp.exmail.qq.com
    host: smtp.163.com
    # 使用自己的发送方用户名 + 授权码填充
    #spring.mail.port不指定；spring.mail.password不是邮箱密码，需要登录mail.163.com，前往设置 客户端授权密码中获取的一个16个字符的密码，同时允许POP3/SMTP服务。
    username: qingyunpang@163.com
    password: HNWCNOQUOGEUPNCS
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true