secure:
  ignore:
    urls: #安全路径白名单
      - /222  #允许路径为 /222的跳过SpringSecurity权限




server:
  port: 8002
spring:
  profiles:
    active: druid
  redis:
    port: 6379
    host: 192.168.236.131
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    #password: "123456"
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
  mvc:
    pathmatch:
      matching-strategy: ant\_path\_matcher   #解决 PatternsRequestCondition.getPatterns()“ because “this.condition“ is null的问题
mybatis-plus:
  global-config:
    db-config: #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #查看生产的sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml
