server:
  port: 8008

spring:
  profiles:
    active: druid # 环境设置
  application:
    name: mybatis_plus # 服务名

mybatis-plus: #mybatis
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 查看生产的sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler   #通用枚举的默认处理器
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/xml/*Mapper.xml
  type-enums-package: com.xufei.demo.enums