server:
  port: 8008

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: mybatis_plus # 服务名
  datasource: # mysql数据库连接
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.236.131:3306/girls?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1234

mybatis-plus: #mybatis
  configuration:
    # 查看生产的sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler   #通用枚举的默认处理器
  global-config:
    db-config: #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/xml/*Mapper.xml
  type-enums-package: com.xufei.demo.enums